server:
  http_listen_port: 9080  # Port for Promtail to expose metrics
  grpc_listen_port: 0     # Disable gRPC

positions:
  filename: positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push 

scrape_configs:
  - job_name: "api_logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "api"
          __path__: swagger_server/api.log
