openapi: 3.0.0
info:
  title: Subject API
  description: API to manage university subjects.
  version: 1.0.0
servers:
- url: http://localhost:8000
  description: Development server
paths:
  /subjects:
    get:
      summary: Retrieve a list of subjects
      description: Fetch a list of all the subjects in the curriculum.
      operationId: subjects_get
      responses:
        "200":
          description: A list of subjects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subject'
                x-content-type: application/json
        "500":
          description: Server error
      x-openapi-router-controller: swagger_server.controllers.default_controller
    post:
      summary: Add a new subject
      description: Add a new subject to the curriculum.
      operationId: subjects_post
      requestBody:
        description: Subject information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subject'
        required: true
      responses:
        "201":
          description: Subject created successfully
        "400":
          description: Invalid input
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /subjects/{subjectId}:
    get:
      summary: Get a specific subject
      description: Fetch details of a specific subject using its ID.
      operationId: subjects_subject_id_get
      parameters:
      - name: subjectId
        in: path
        description: ID of the subject to retrieve
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Subject details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subject'
        "404":
          description: Subject not found
      x-openapi-router-controller: swagger_server.controllers.default_controller
    put:
      summary: Update a subject
      description: Update the details of an existing subject.
      operationId: subjects_subject_id_put
      parameters:
      - name: subjectId
        in: path
        description: ID of the subject to update
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        description: Updated subject information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subject'
        required: true
      responses:
        "200":
          description: Subject updated successfully
        "400":
          description: Invalid input
        "404":
          description: Subject not found
      x-openapi-router-controller: swagger_server.controllers.default_controller
    delete:
      summary: Delete a subject
      description: Delete a specific subject from the library using its ID.
      operationId: subjects_subject_id_delete
      parameters:
      - name: subjectId
        in: path
        description: ID of the subject to delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: Subject deleted successfully
        "404":
          description: Subject not found
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Subject:
      required:
      - code
      - credits
      - department
      - title
      type: object
      properties:
        id:
          type: integer
          description: Unique ID of the subject
        code:
          type: string
          description: "The code of the subject (e.g., CS101)"
        title:
          type: string
          description: The title of the subject
        description:
          type: string
          description: A brief description of the subject
        department:
          type: string
          description: The department offering the subject
        credits:
          type: number
          description: Number of credits for the subject
          format: float
      example:
        id: 1
        code: ИСРПО
        title: Инструментальные средства разработки ПО
        description: Предмет посвящен изучению инструментов и средств для разработки
          ПО.
        department: ФИТиП
        credits: 3

