name: Test Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask app in background
        run: |
          python3 -m swagger_server &
          echo $! > flask_pid

          - name: Test GET query and response
          run: |
            sleep 5  # Give the server time to start
            response_code=$(curl -s -o /dev/null -w "%{http_code}" -X GET http://localhost:8080/subjects)
            if [ "$response_code" -eq 200 ]; then
              echo "GET query succeeded with status code 200.";
            else
              echo "GET query failed with status code $response_code.";
              kill $(cat flask_pid);
              exit 1;
            fi        

      - name: Clean up Flask process
        if: always()
        run: |
          kill $(cat flask_pid) || true
          rm flask_pid
